version: 2
jobs:
  build:
    working_directory: ~/sms-tool-server
    docker:
      - image: circleci/node:10.13
      - image: mongo:4.2.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: "Install NPM packages"
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
